version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: farhanisrakyen.com/php
        container_name: app
        tty: true
        restart: unless-stopped
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./docker/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis

    db:
        image: mysql:8.0
        container_name: db
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www/html/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        command: redis-server --appendonly yes --requirepass  "${REDIS_PASSWORD}"
        ports:
            - 6379:6379

    rabbitmq:
        image: "rabbitmq:management"
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_LOGIN}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    db-data: ~
